### ISSUE TITLE
Internal failure: VerificationError (cryptography)

### ISSUE THREAD

**Issue by fkalbe** [duecredit/duecredit#142]
Hi, 

I'm trying to follow the PyMVPA tutorial (http://www.pymvpa.org/tutorial.html), but the first import already fails due to an internal duecredit error:

`from mvpa2.tutorial_suite import *`

gives:

```
2019-01-18 11:00:43,590 [WARNING] DueCredit internal failure while running <function _get_inactive_due at 0x7f651a76b0c8>: VerificationError("importing '/usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_813c10e0x7adb75f8.x86_64-linux-gnu.so': /usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_813c10e0x7adb75f8.x86_64-linux-gnu.so: symbol SSLv2_client_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:199)
2019-01-18 11:00:44,258 [WARNING] DueCredit internal failure while running <function _get_active_due at 0x7f651a76b1b8>: VerificationError("importing '/usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_813c10e0x7adb75f8.x86_64-linux-gnu.so': /usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_813c10e0x7adb75f8.x86_64-linux-gnu.so: symbol SSLv2_client_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:199)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/mvpa2/__init__.py", line 179, in <module>
    due.cite(
AttributeError: 'DueSwitch' object has no attribute 'cite'
```

It seems to me like this is a problem with duecredit and not PyMVPA, so I'm opening the issue here. I'm running a VirtualBox instance with NeuroDebian 8.0.0 (64-bit) and Python 2.7.9. Not really sure what's the issue, so any help would be appreciated. Thanks!

**Comment by fkalbe** [comment]
The error seems to be caused by an outdated openssl version, which I could resolve by updating the package. I will leave the issue open for now in case you might want to improve how this error is handled by duecredit.

**Comment by yarikoptic** [comment]
Thank you @fkalbe !  We also got similar report now on pymvpa which finally triggered my attention -- hint on upgrading openssl helped, but altogether this issue shows that we still need to close a possible hole in how to make duecredit 100% robust in not causing trouble to projects using it.

**Comment by yarikoptic** [comment]
FWIW 0.6.5 released, uploaded to pypi and neurodebian.
