### ISSUE TITLE
DueCredit internal failure while running <function DueSwitch.dump ... on Windows 10

### ISSUE THREAD

**Issue by rly** [duecredit/duecredit#173]
I wrote a test script `test_due.py` which contains just `import numpy`

When I try to run `duecredit` on this script, I get the error below.

Am I doing something incorrectly?

Environment:
Python 3.8.5
miniconda
Windows 10
duecredit 0.8.0

```bash
$ conda create --name test_due python=3.8 --yes
$ conda activate test_due
$ pip install duecredit numpy==1.19.1
$ python -m duecredit test_due.py
```
```
DueCredit Report:
- Scientific tools library / numpy (v 1.19.1) [1]

1 package cited
0 modules cited
0 functions cited

References
----------

[1] 2020-12-02 16:27:24,631 [WARNING] DueCredit internal failure while running <function DueSwitch.dump at 0x00000273D5DC7310>: UnicodeDecodeError('charmap', b'{\n    "primary-dialects": {\n        "af": "af-ZA",\n        "ar": "ar",\n        "bg": "bg-BG",\n        "ca": "ca-AD",\n        "cs": "cs-CZ",\n        "cy": "cy-GB",\n        "da": "da-DK",\n        "de": "de-DE",\n        "el": "el-GR",\n        "en": "en-US",\n        "es": "es-ES",\n        "et": "et-EE",\n        "eu": "eu",\n        "fa": "fa-IR",\n        "fi": "fi-FI",\n        "fr": "fr-FR",\n        "he": "he-IL",\n
"hr": "hr-HR",\n        "hu": "hu-HU",\n        "id": "id-ID",\n        "is": "is-IS",\n        "it": "it-IT",\n        "ja": "ja-JP",\n        "km": "km-KH",\n        "ko": "ko-KR",\n        "lt": "lt-LT",\n        "lv": "lv-LV",\n        "mn": "mn-MN",\n        "nb": "nb-NO",\n        "nl": "nl-NL",\n        "nn": "nn-NO",\n        "pl": "pl-PL",\n        "pt": "pt-PT",\n        "ro": "ro-RO",\n        "ru": "ru-RU",\n        "sk": "sk-SK",\n
      "sl": "sl-SI",\n        "sr": "sr-RS",\n        "sv": "sv-SE",\n        "th": "th-TH",\n        "tr": "tr-TR",\n        "uk": "uk-UA",\n
"vi": "vi-VN",\n        "zh": "zh-CN"\n    },\n    "language-names": {\n        "af-ZA": [\n            "Afrikaans",\n            "Afrikaans"\n
 ],\n        "ar": [\n            "\xd8\xa7\xd9\x84\xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9",\n            "Arabic"\n        ],\n        "bg-BG": [\n
           "\xd0\x91\xd1\x8a\xd0\xbb\xd0\xb3\xd0\xb0\xd1\x80\xd1\x81\xd0\xba\xd0\xb8",\n            "Bulgarian"\n        ],\n        "ca-AD": [\n
       "Catal\xc3\xa0",\n            "Catalan"\n        ],\n        "cs-CZ": [\n            "\xc4\x8ce\xc5\xa1tina",\n            "Czech"\n        ],\n        "cy-GB": [\n            "Cymraeg",\n            "Welsh"\n        ],\n        "da-DK": [\n            "Dansk",\n            "Danish"\n
],\n        "de-AT": [\n            "Deutsch (\xc3\x96sterreich)",\n            "German (Austria)"\n        ],\n        "de-CH": [\n            "Deutsch (Schweiz)",\n            "German (Switzerland)"\n        ],\n        "de-DE": [\n            "Deutsch (Deutschland)",\n            "German (Germany)"\n        ],\n        "el-GR": [\n            "\xce\x95\xce\xbb\xce\xbb\xce\xb7\xce\xbd\xce\xb9\xce\xba\xce\xac",\n            "Greek"\n        ],\n
        "en-GB": [\n            "English (UK)",\n            "English (UK)"\n        ],\n        "en-US": [\n            "English (US)",\n
"English (US)"\n        ],\n        "es-CL": [\n            "Espa\xc3\xb1ol (Chile)",\n            "Spanish (Chile)"\n        ],\n        "es-ES": [\n
            "Espa\xc3\xb1ol (Espa\xc3\xb1a)",\n            "Spanish (Spain)"\n        ],\n        "es-MX": [\n            "Espa\xc3\xb1ol (M\xc3\xa9xico)",\n            "Spanish (Mexico)"\n        ],\n        "et-EE": [\n            "Eesti",\n            "Estonian"\n        ],\n        "eu": [\n
        "Euskara",\n            "Basque"\n        ],\n        "fa-IR": [\n            "\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c",\n            "Persian"\n        ],\n        "fi-FI": [\n            "Suomi",\n            "Finnish"\n        ],\n        "fr-CA": [\n            "Fran\xc3\xa7ais (Canada)",\n            "French (Canada)"\n        ],\n        "fr-FR": [\n            "Fran\xc3\xa7ais (France)",\n            "French (France)"\n        ],\n        "he-IL": [\n            "\xd7\xa2\xd7\x91\xd7\xa8\xd7\x99\xd7\xaa",\n            "Hebrew"\n        ],\n        "hr-HR": [\n            "Hrvatski",\n            "Croatian"\n        ],\n        "hu-HU": [\n            "Magyar",\n            "Hungarian"\n        ],\n        "id-ID": [\n
     "Bahasa Indonesia",\n            "Indonesian"    \n        ],\n        "is-IS": [\n            "\xc3\x8dslenska",\n            "Icelandic"\n
   ],\n        "it-IT": [\n            "Italiano",\n            "Italian"\n        ],\n        "ja-JP": [\n            "\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e",\n            "Japanese"\n        ],\n        "km-KH": [\n            "\xe1\x9e\x97\xe1\x9e\xb6\xe1\x9e\x9f\xe1\x9e\xb6\xe1\x9e\x81\xe1\x9f\x92\xe1\x9e\x98\xe1\x9f\x82\xe1\x9e\x9a",\n            "Khmer"\n        ],\n        "ko-KR": [\n            "\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4",\n
         "Korean"\n        ],\n        "lt-LT": [\n            "Lietuvi\xc5\xb3",\n            "Lithuanian"\n        ],\n        "lv-LV": [\n
   "Latvie\xc5\xa1u",\n            "Latvian"\n        ],\n        "mn-MN": [\n            "\xd0\x9c\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xbe\xd0\xbb",\n
     "Mongolian"\n        ],\n        "nb-NO": [\n            "Norsk bokm\xc3\xa5l",\n            "Norwegian (Bokm\xc3\xa5l)"\n        ],\n        "nl-NL": [\n            "Nederlands",\n            "Dutch"\n        ],\n        "nn-NO": [\n            "Norsk nynorsk",\n            "Norwegian (Nynorsk)"\n        ],\n        "pl-PL": [\n            "Polski",\n            "Polish"\n        ],\n        "pt-BR": [\n            "Portugu\xc3\xaas (Brasil)",\n            "Portuguese (Brazil)"\n        ],\n        "pt-PT": [\n            "Portugu\xc3\xaas (Portugal)",\n            "Portuguese (Portugal)"\n        ],\n        "ro-RO": [\n            "Rom\xc3\xa2n\xc4\x83",\n            "Romanian"\n        ],\n        "ru-RU": [\n            "\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9",\n            "Russian"\n        ],\n        "sk-SK": [\n            "Sloven\xc4\x8dina",\n
  "Slovak"\n        ],\n        "sl-SI": [\n            "Sloven\xc5\xa1\xc4\x8dina",\n            "Slovenian"\n        ],\n        "sr-RS": [\n
     "\xd0\xa1\xd1\x80\xd0\xbf\xd1\x81\xd0\xba\xd0\xb8 / Srpski",\n            "Serbian"\n        ],\n        "sv-SE": [\n            "Svenska",\n
        "Swedish"\n        ],\n        "th-TH": [\n            "\xe0\xb9\x84\xe0\xb8\x97\xe0\xb8\xa2",\n            "Thai"\n        ],\n        "tr-TR": [\n            "T\xc3\xbcrk\xc3\xa7e",\n            "Turkish"\n        ],\n        "uk-UA": [\n            "\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd1\x97\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0",\n            "Ukrainian"\n        ],\n        "vi-VN": [\n            "Ti\xe1\xba\xbfng Vi\xe1\xbb\x87t",\n            "Vietnamese"\n        ],\n        "zh-CN": [\n            "\xe4\xb8\xad\xe6\x96\x87 (\xe4\xb8\xad\xe5\x9b\xbd\xe5\xa4\xa7\xe9\x99\x86)",\n            "Chinese (PRC)"\n        ],\n        "zh-TW": [\n            "\xe4\xb8\xad\xe6\x96\x87 (\xe5\x8f\xb0\xe7\x81\xa3)",\n            "Chinese (Taiwan)"\n        ]\n    }\n}\n', 1266, 1267, 'character maps to <undefined>'). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:192)
```

**Comment by yarikoptic** [comment]
thanks @rly!  So it is some unicode fiasco , and somehow windows specific -- worked out for me just fine on my laptop

<details>
<summary>locale here</summary> 

```shell
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
</details>

but similarly crashed on windows VM in git bash (I saw those `$`) with 
<details>
<summary>locale</summary> 

```shell
DataLad@DESKTOP-1FTT289 MINGW64 ~/PycharmProjects/datalad (enh-nofakedatescheck)
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```
</details>

I will try to digest all the information present about this e.g. https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console and come up with a fix (unless may be you immediately see what we should be doing here in a windows-specific way)

**Comment by rly** [comment]
The issue seems to lie in citeproc-py. I have version 0.5.1. If I just open a Python 3.8 terminal and call `import citeproc` on Windows, I get:
```
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import citeproc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\site-packages\citeproc\__init__.py", line 43, in <module>
    locales_json = json.load(file)
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1266: character maps to <undefined>
```

**Comment by rly** [comment]
I filed an issue ticket for this in citeproc-py: https://github.com/brechtm/citeproc-py/issues/106

**Comment by rly** [comment]
After applying the suggested fix, the output of `python -m duecredit test_due.py` looks correct.

**Comment by yarikoptic** [comment]
awesome -- thank you for the proposed fix for citeproc_py!  I will keep it in mind so we could progress/release citeproc as soon as it is fixed up.  I do not think there is anything we could do on duecredit side (at least tricks I have tried had no effect), so I will close this one
