### ISSUE TITLE
Syntax error in test_utils.py with python 2.7.6

### ISSUE THREAD

**Issue by mvdoc** [duecredit/duecredit#26]
We didn't catch this I believe because travis skips it.

```
uecredit.tests.test_injections.test_injector_del ... ok
duecredit.tests.test_io.test_import_doi ... ok
duecredit.tests.test_io.test_pickleoutput ... ok
duecredit.tests.test_io.test_text_output ... ok
duecredit.tests.test_io.test_text_output_dump_formatting ... ok
Failure: SyntaxError (unqualified exec is not allowed in function '_test_external' it is a nested function (test_utils.py, line 57)) ... ERROR

======================================================================
ERROR: Failure: SyntaxError (unqualified exec is not allowed in function '_test_external' it is a nested function (test_utils.py, line 57))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/contematto/virtualenv/duecredit/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/contematto/virtualenv/duecredit/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/contematto/virtualenv/duecredit/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
SyntaxError: unqualified exec is not allowed in function '_test_external' it is a nested function (test_utils.py, line 57)

----------------------------------------------------------------------
Ran 37 tests in 7.152s

FAILED (errors=1)
```

**Comment by yarikoptic** [comment]
neither skips nor fails for me:
```
$>  venv/bin/python /usr/bin/nosetests -v duecredit/tests/test_io.py 
duecredit.tests.test_io.test_import_doi ... ok
duecredit.tests.test_io.test_pickleoutput ... ok
duecredit.tests.test_io.test_text_output ... ok
duecredit.tests.test_io.test_text_output_dump_formatting ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.023s

OK

$> git describe
0.2.2-12-g903c496
```
and I remember fixing smth like that recently -- are you sure you are on up to date master? ;)

**Comment by yarikoptic** [comment]
r is it my better python?
```
$> python --version
Python 2.7.10
```

**Comment by yarikoptic** [comment]
doh -- that was about different test module, but the observation stands:
```
$> venv/bin/python /usr/bin/nosetests -sv duecredit/tests/test_utils.py
duecredit.tests.test_utils.test_external_versions_basic ... ok
duecredit.tests.test_utils.test_external_versions_unknown ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('scipy',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('numpy',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('mvpa2',) ... SKIP: External mvpa2 not present
duecredit.tests.test_utils.test_external_versions_popular_packages('sklearn',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('statsmodels',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('pandas',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('matplotlib',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('psychopy',) ... fatal: Not a git repository (or any of the parent directories): .git
ok

----------------------------------------------------------------------
Ran 10 tests in 0.439s

OK (SKIP=1)
```

so those which it skips for me it skips for a valid reason

**Comment by mvdoc** [comment]
yep up to date...

```
(duecredit)contematto@talete ~/github/duecredit (master*) $ python --version
Python 2.7.6

(duecredit)contematto@talete ~/github/duecredit (master*) $ nosetests -s -v duecredit/tests/test_utils.py
Failure: SyntaxError (unqualified exec is not allowed in function '_test_external' it is a nested function (test_utils.py, line 57)) ... ERROR

======================================================================
ERROR: Failure: SyntaxError (unqualified exec is not allowed in function '_test_external' it is a nested function (test_utils.py, line 57))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/contematto/virtualenv/duecredit/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/contematto/virtualenv/duecredit/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/contematto/virtualenv/duecredit/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
SyntaxError: unqualified exec is not allowed in function '_test_external' it is a nested function (test_utils.py, line 57)

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

(duecredit)contematto@talete ~/github/duecredit (master*) $ git describe
0.2.2-12-g903c496
```

but it works with python 2.7.9

```
contematto@talete ~/github/duecredit (master*) $ python --version
Python 2.7.9 :: Anaconda 2.3.0 (x86_64)
contematto@talete ~/github/duecredit (master*) $ nosetests -s -v duecredit/tests/test_utils.py
duecredit.tests.test_utils.test_external_versions_basic ... ok
duecredit.tests.test_utils.test_external_versions_unknown ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('scipy',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('numpy',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('mvpa2',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('sklearn',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('statsmodels',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('pandas',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('matplotlib',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('psychopy',) ... SKIP: External psychopy not present

----------------------------------------------------------------------
Ran 10 tests in 1.190s

OK (SKIP=1)
```

**Comment by yarikoptic** [comment]
so we should skip the test on that particular version of python.  Is that the base python on OSX?

**Comment by mvdoc** [comment]
I believe so

**Comment by yarikoptic** [comment]
make it happen! ;)

**Comment by mvdoc** [comment]
Will do

**Comment by mvdoc** [comment]
For some reason now it works, without any changes...

```
(duecredit)contematto@talete ~/github/duecredit (master*) $ nosetests -s -v duecredit/tests/test_utils.py
duecredit.tests.test_utils.test_external_versions_basic ... ok
duecredit.tests.test_utils.test_external_versions_unknown ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('scipy',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('numpy',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('mvpa2',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('sklearn',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('statsmodels',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('pandas',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('matplotlib',) ... ok
duecredit.tests.test_utils.test_external_versions_popular_packages('psychopy',) ... SKIP: External psychopy not present

----------------------------------------------------------------------
Ran 10 tests in 1.091s

OK (SKIP=1)
(duecredit)contematto@talete ~/github/duecredit (master*) $ python --version
Python 2.7.6
```
