### ISSUE TITLE
test_noincorrect_import_if_no_lxml fails on my laptop (and on travis)

### ISSUE THREAD

**Issue by mvdoc** [duecredit/duecredit#84]
I get the same error on my laptop and on travis (see https://travis-ci.org/duecredit/duecredit/jobs/128580818)

```
======================================================================
FAIL: duecredit.tests.test_api.test_noincorrect_import_if_no_lxml
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/contematto/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/contematto/github/duecredit/duecredit/tests/test_api.py", line 82, in test_noincorrect_import_if_no_lxml
    assert_equal(ret, 1)
AssertionError: 0 != 1

======================================================================
FAIL: duecredit.tests.test_api.test_noincorrect_import_if_no_lxml_numpy({'cmd': 'import duecredit; import numpy as np; print("done123")'}, {'DUECREDIT_ENABLE': 'yes'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/contematto/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/contematto/github/duecredit/duecredit/tests/test_api.py", line 107, in check_noincorrect_import_if_no_lxml_numpy
    assert_in('For formatted output we need citeproc', out)
AssertionError: 'For formatted output we need citeproc' not found in u"done123\n\nDueCredit Report:\n- Scientific tools library / scipy (v 0.14) [1]\n  - Single linkage hierarchical clustering / scipy.cluster.hierarchy:linkage (v 0.14) [2]\n\n1 packages cited\n0 modules cited\n1 functions cited\n\nReferences\n----------\n\n[1] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.\n[2] 2016-05-07 19:23:58,362 [WARNING] DueCredit internal failure while running <function _dump_collector_summary at 0x102491a28>: UnicodeEncodeError('ascii', u'Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link cluster method. The Computer Journal, 16(1), pp.30\\u201334.', 128, 129, 'ordinal not in range(128)'). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:76)\n"

======================================================================
FAIL: duecredit.tests.test_api.test_noincorrect_import_if_no_lxml_numpy({'script': '/Users/contematto/github/duecredit/duecredit/tests/envs/stubbed/script.py'}, {'DUECREDIT_ENABLE': 'yes'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/contematto/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/contematto/github/duecredit/duecredit/tests/test_api.py", line 107, in check_noincorrect_import_if_no_lxml_numpy
    assert_in('For formatted output we need citeproc', out)
AssertionError: 'For formatted output we need citeproc' not found in u"done123\n\nDueCredit Report:\n- Scientific tools library / scipy (v 0.14) [1]\n  - Single linkage hierarchical clustering / scipy.cluster.hierarchy:linkage (v 0.14) [2]\n- Machine Learning library / sklearn (v 0.15.2) [3]\n\n2 packages cited\n0 modules cited\n1 functions cited\n\nReferences\n----------\n\n[1] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.\n[2] 2016-05-07 19:23:59,233 [WARNING] DueCredit internal failure while running <function _dump_collector_summary at 0x101497c08>: UnicodeEncodeError('ascii', u'Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link cluster method. The Computer Journal, 16(1), pp.30\\u201334.', 128, 129, 'ordinal not in range(128)'). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:76)\n"
```

**Comment by mvdoc** [comment]
OK, I fixed it on my laptop. I think it was because of setting up a virtualenv with `--system-site-packages` which resulted in having lxml installed system-wide, and citeproc-py only in the virtualenv. However, why does it fail on travis in the same way (and only for my prs?)

**Comment by yarikoptic** [comment]
see https://github.com/duecredit/duecredit/pull/83#issuecomment-217677724 for my explanation of what is happening ;)

**Comment by mvdoc** [comment]
ok sorry for the noise
